[package]
name = "WCM-UI"
version = "1.0.0"
edition = "2021"

[dependencies]
clipboard = "0.5.0"
gio = "0.20.6"
gtk = { version = "0.9.4", package = "gtk4", features = ["v4_12"] }
unicode-segmentation = "1.12.0"
rand = "0.8.5"